name: Publish Python 🐍 distribution 📦 to PyPI

# This trigger runs the workflow on every push to any branch.
# Remove or adjust the branches as needed.
on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Setup with Python 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Deploy to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: bash ./ci/deploy_to_pypi.sh
