name: CI/CD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Build Package
        run: |
          python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
